
-----------QUETION 1----------

SELECT * FROM SALES.CUSTOMERS ORDER BY FIRST_NAME DESC
------------QUETION 2--------------
SELECT CITY,FIRST_NAME,LAST_NAME FROM SALES.CUSTOMERS 

--------QUETION 3-------
SELECT TOP(3) * FROM PRODUCTION.PRODUCTS ORDER BY LIST_PRICE

------QUETION 4----------

SELECT * FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE>300 AND MODEL_YEAR='2018'

--------QUETION 5------------
SELECT * FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE>300 AND MODEL_YEAR='2018'

-----------QUETION 6------------

SELECT * FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE BETWEEN 1899 AND 1999.99

---------QUETION 7--------
SELECT * FROM PRODUCTION.PRODUCTS WHERE LIST_PRICE IN(299.99,466.99,489.99)

---------QUETION 8------------
SELECT * FROM SALES.CUSTOMERS WHERE LAST_NAME LIKE '[ABC]%';

----------QUETION 9-----------
SELECT * FROM SALES.CUSTOMERS WHERE FIRST_NAME NOT LIKE 'A%';

-------------QUETION 10-----------

SELECT CITY,STATE,COUNT(CUSTOMER_ID)  AS 'CUSTOMER NUMBER' FROM SALES.CUSTOMERS GROUP BY CITY,STATE


------------QUETION 11-----------

SELECT CUSTOMER_ID,YEAR(ORDER_DATE) ,COUNT(ORDER_ID) AS 'CUSTOMER NUMBER' FROM SALES.ORDERS GROUP BY CUSTOMER_ID,YEAR(ORDER_DATE)

-----------QUETION 12-------

SELECT CATEGORY_ID ,MAX(LIST_PRICE) AS MAX_LIST_PRICE,MIN(LIST_PRICE) AS MIN_LIST_PRICE FROM PRODUCTION.PRODUCTS 
GROUP BY CATEGORY_ID HAVING(MAX(LIST_PRICE)>4000 OR MIN(LIST_PRICE)<500)





