 
 -----------QUETION 1----------
 CREATE VIEW SALES_INFO
 AS
 SELECT P.PRODUCT_NAME,SI.ITEM_ID,SO.ORDER_ID
 FROM PRODUCTION.PRODUCTS P  INNER JOIN  SALES.ORDER_ITEMS SI ON P.PRODUCT_ID=SI.ITEM_ID 
 INNER JOIN SALES.ORDERS SO ON SI.ITEM_ID=SO.ORDER_ID

 SELECT * FROM SALES_INFO

 ---------QUETION 2-------------
 CREATE VIEW STAFF_SALES 
 AS
 SELECT SS.FIRST_NAME,SS.LAST_NAME,COUNT(QUANTITY*LIST_PRICE) AS 'ORDER VALUE'
 FROM SALES.ORDERS SO INNER JOIN SALES.ORDER_ITEMS SI ON SO.ORDER_ID=SI.ORDER_ID
 INNER JOIN SALES.STAFFS SS ON SS.STAFF_ID=SO.STAFF_ID
 GROUP BY SS.FIRST_NAME,SS.LAST_NAME

 SELECT * FROM STAFF_SALES

 ---------------QUETION 3--------------

 ALTER PROCEDURE USP_ADD_STORE
 @STORE_NAME VARCHAR(20),
 @STORE_COUNT INT OUTPUT
 AS
 BEGIN
 INSERT INTO SALES.STORES(store_NAME) VALUES(@STORE_NAME)
 SELECT @STORE_COUNT=COUNT(*) FROM SALES.STORES
 END;

 DECLARE @COUNT INT;
 EXEC USP_ADD_STORE
 @STORE_NAME='ABC',
@STORE_COUNT=@COUNT OUTPUT
SELECT @COUNT AS 'STORE COUNT'

 SELECT * FROM SALES.STORES

 -----------------QUETION 4--------------

 CREATE PROCEDURE USP_STORE_WISE_SALES
 AS
 BEGIN
 SELECT SS.STORE_ID,SS.STORE_NAME,SS.CITY,COUNT(SO.ORDER_ID) AS 'ORDER COUNT' 
 FROM SALES.STORES SS INNER JOIN SALES.ORDERS SO ON SS.STORE_ID=SO.STORE_ID 
 GROUP BY SS.STORE_ID,SS.STORE_NAME,SS.CITY
 END;

 EXEC  USP_STORE_WISE_SALES

 -------------QUETION 5--------------

 CREATE FUNCTION UDF_AVG_QTY(
@QUANTITY INT,
@LIST_PRICE DEC(10,2)
) 
RETURNS DEC(10,2)
AS
BEGIN
   RETURN @QUANTITY* @LIST_PRICE
END
SELECT  UDF_AVG_QTY(20,100) AS 'AVG SALE'
SELECT PRODUCT_ID,PRODUCT_NAME,AVG(QUANTITY*LIST_PRICE) AS 'TOTAL BILL' FROM UDF_AVG_QTY
SELECT PRODUCT_ID,PRODUCT_NAME,(SALES.UDF_NETSALE(QUANTITY,LIST_PRICE)) AS 'TOTAL BILL'
 FROM UDF_AVG_QTY GROUP BY PRODUCT_ID
  
ALTER FUNCTION UDF_AVG_QTY(
@CUSTOMER_ID INT,
@LIST_PRICE DEC(10,2)
)
RETURNS DEC(10,2)
AS
BEGIN
SELECT UDF_AVG_QTY(1,200) AS 'AVG SALE'
SELECT PP.PRODUCT_ID,PP.PRODUCT_NAME,



 
 
 


