------------------FUNCTIONS--------------------
SELECT AVG(LIST_PRICE) AS 'AVG PRICE' FROM PRODUCTION.PRODUCTS
SELECT COUNT(*) AS 'CUSTOMER COUNT' FROM SALES.CUSTOMERS
SELECT MAX(LIST_PRICE) AS 'MAX_PRICE' FROM PRODUCTION.PRODUCTS
SELECT MIN(LIST_PRICE) AS 'MAX_PRICE' FROM PRODUCTION.PRODUCTS
SELECT SUM(QUANTITY*LIST_PRICE) AS 'TOTAL SALE' FROM SALES.ORDER_ITEMS
SELECT SUM(QUANTITY) AS 'TOTAL SOLD QUANTITY' FROM SALES.ORDER_ITEMS
WHERE PRODUCT_ID=177

--------------DATE TIME FUNCTIONS----------

SELECT GETDATE()
SELECT SYSDATETIME()
SELECT DATENAME(MONTH,GETDATE())
SELECT DAY(GETDATE())
SELECT MONTH(GETDATE())
SELECT YEAR(GETDATE())
SELECT ORDER_ID,CUSTOMER_ID,MONTH(ORDER_DATE) AS 'MONTH',YEAR(ORDER_DATE) AS 'YEAR' FROM SALES.ORDERS

DECLARE @D DATETIME='10-17-1800';
SELECT DATEDIFF(DAY,@D,GETDATE())

SELECT ORDER_DATE,SHIPPED_DATE,DATEDIFF(DAY,ORDER_DATE,SHIPPED_DATE) AS 'DAY' FROM SALES.ORDERS

SELECT DATEADD(DAY,10,GETDATE()) AS 'ADD'

SELECT EOMONTH(GETDATE(),0);
SELECT ISDATE('13-01-2019')

----------------------STRING -------------

SELECT ASCII('B')
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS 'NAME' FROM SALES.CUSTOMERS
SELECT REPLACE('A WANT TO HAVRE A CUP OF COFFEE','COFFEE','TEA')







