

-------------UDF SCALAR FUNCTIONS---------
CREATE FUNCTION SALES.UDF_NETSALE(
@QUANTITY INT,
@LIST_PRICE DEC(10,2)
) 
RETURNS DEC(10,2)
AS
BEGIN
   RETURN @QUANTITY * @LIST_PRICE
END

SELECT  SALES.UDF_NETSALE(30,100) AS 'NET SALE'

SELECT ORDER_ID,(QUANTITY*LIST_PRICE) AS 'TOTAL BILL' FROM SALES.ORDER_ITEMS

SELECT ORDER_ID,(SALES.UDF_NETSALE(QUANTITY,LIST_PRICE)) AS 'TOTAL BILL' FROM SALES.ORDER_ITEMS


-------TABLE VARIABLE--------

DECLARE @PRODUCT_TABLE TABLE(
PRODUCET_NAME VARCHAR(MAX) NOT NULL,-----NOT USE PRIMARY KEY IF TYPE IS MAX-----------
BRAND_ID INT NOT NULL,
LIST_PRICE DEC(10,2) NOT NULL
);
INSERT INTO @PRODUCT_TABLE 
SELECT product_name,brand_id,list_price FROM PRODUCTION.PRODUCTS WHERE product_id=2;
SELECT * FROM @PRODUCT_TABLE


--------------WINDOW FUNCTION--------------
SELECT PRODUCT_ID,PRODUCT_NAME,LIST_PRICE ,
RANK() OVER(ORDER BY LIST_PRICE DESC) AS 'RANK'
FROM PRODUCTION.PRODUCTS



