
----------------------------------------------TRIGGER-----------------------------
CREATE TABLE PRODUCTION.PRODUCTS_AUDITS(
CHANGE_ID   INT IDENTITY PRIMARY KEY,
PRODUCT_ID   INT NOT NULL,
PRODUCT_NAME   VARCHAR(255),
BRAND_ID      INT NOT NULL,
CATEGORY_ID   INT NOT NULL,
MODEL_YEAR  INT NOT NULL,
LIST_PRICE   DECIMAL(10,2) NOT NULL,
UPDATED_AT   DATETIME NOT NULL,
OPERATION    CHAR(3) NOT NULL,
CHECK(OPERATION='INS' OR OPERATION='DEL')
)

CREATE TRIGGER PRODUCTION.TRG_PRODUCT_AUDIT
ON PRODUCTION.PRODUCTS
AFTER INSERT,DELETE
AS 
BEGIN
  INSERT INTO PRODUCTION.PRODUCTS_AUDITS(

  PRODUCT_ID , 
  PRODUCT_NAME,
  BRAND_ID    ,
  CATEGORY_ID ,
  MODEL_YEAR , 
  LIST_PRICE , 
  UPDATED_AT , 
  OPERATION   
  )SELECT  
  I.PRODUCT_ID,I.PRODUCT_NAME,I.BRAND_ID,I.CATEGORY_ID,I.MODEL_YEAR ,I.LIST_PRICE,GETDATE(),'INS'
  FROM
  INSERTED I
  UNION ALL
  SELECT
  D.PRODUCT_ID,D.PRODUCT_NAME,D.BRAND_ID,D.CATEGORY_ID,D.MODEL_YEAR ,D.LIST_PRICE,GETDATE(),'DEL'
  FROM
  DELETED D;
  END

  INSERT INTO PRODUCTION.PRODUCTS 
  (PRODUCT_NAME,BRAND_ID,CATEGORY_ID,MODEL_YEAR,LIST_PRICE)
  VALUES('HELMET',1,1,2019,700)

  SELECT * FROM production.PRODUCTS_AUDITS

  DELETE FROM PRODUCTION.PRODUCTS_AUDITS WHERE PRODUCT_ID=373
  SELECT * FROM production.PRODUCTS_AUDITS

  ----------------------------------------
  CREATE TRIGGER SALES.ORDER_ITEMS_AUDIT
  ON SALES.ORDER_ITEMS
  AFTER INSERT,DELETE
  AS
  BEGIN
  INSERT INTO  PRODUCTION.STOCKS(
  PRODUCT_ID,
  QUANTITY,
  OPERATION
  )
  SELECT I.PRODUCT_ID,I.QUANTITY,'INS'
  FROM
  INSERTED I
  UNION ALL
  SELECT D.PRODUCT_ID,D.QUANTITY,'DEL'
  FROM
  DELETED D
  END

  INSERT INTO SALES.ORDER_ITEMS
  (order_id,item_id,product_id,QUANTITY,list_price)
  VALUES(10,3,5,600,900)

  SELECT * FROM SALES.ORDER_ITEMS_AUDIT
  
