-------------CREATION DATE:18-OCT-2019---
------AUTHOR:POOJA
------DESCRIPTION--TO DISPLAY PRODUCT LIST-------
CREATE PROCEDURE USP_PRODUCTLIST
---DECLARE PARAMETERS---
AS
BEGIN
---BODY OF SP---

SELECT * FROM PRODUCTION.PRODUCTS ORDER BY PRODUCT_NAME
END;

-----ALTER PROCEDURE USP_PRODUCTLIST

---CALLING SP------
 EXECUTE DBO.USP_PRODUCTLIST
 EXEC DBO.USP_PRODUCTLIST
 DBO.USP_PRODUCTLIST

 -----------DROP STORE PRODURE-----------

 DROP DBO.USP_PRODUCTLIST

 =-----------------PARAMETERIZED SP-----------------=

 --CREATION DATE:18-OCT-2019--
 ---AUTHOR:POOJA---
 ---DESCRIPTION:DISPLAY PRODUCTS BY LIST PRICE---
 ALTER PROCEDURE USP_FINDPRODUCT_BY_LISTPRICE
 @LISTPRICE NUMERIC(10,2)
 AS
 BEGIN
      SELECT * FROM PRODUCTION.PRODUCTS 
	  WHERE LIST_PRICE=@LISTPRICE ORDER BY LIST_PRICE
 END

 DBO.USP_FINDPRODUCT_BY_LISTPRICE
  @LISTPRICE=449
 
 ------------INSERT SP--------------
 CREATE PROCEDURE USP_SAVE_BRANDS
 @BRand_name varchar(50)
 AS
 BEGIN
    INSERT INTO PRODUCTION.BRANDS(BRAND_NAME) VALUES(@BRAND_NAME)

	END;
USP_SAVE_BRANDS @BRAND_NAME='STEELBIRDS'

SELECT * FROM PRODUCTION.BRANDS


CREATE PROCEDURE USP_SAVE_CATEGORY
@CATEGORY_NAME VARCHAR(50)
AS
BEGIN
 INSERT INTO PRODUCTION.CATEGORIES(CATEGORY_NAME) VALUES(@CATEGORY_NAME)
 END;

 USP_SAVE_CATEGORY @CATEGORY_NAME='SPORTSBIKE'

 SELECT * FROM PRODUCTION.CATEGORIES

 --------SP WITH OUTPUT PARAMETER----------

 ALTER PROCEDURE USP_SAVE_CATEGORY
@CATEGORY_NAME VARCHAR(50),
@CATERORY_COUNT INT OUTPUT
AS
BEGIN
 INSERT INTO PRODUCTION.CATEGORIES(CATEGORY_NAME) VALUES(@CATEGORY_NAME)
 SELECT @CATERORY_COUNT=COUNT(*) FROM PRODUCTION.CATEGORIES
 
 RETURN @CATERORY_COUNT
 END;

 DECLARE @COUNT INT;
 EXEC USP_SAVE_CATEGORY
 @CATEGORY_NAME='ABC',
@CATERORY_COUNT=@COUNT OUTPUT
SELECT @COUNT AS 'CATERORY COUNT'

 SELECT * FROM PRODUCTION.CATEGORIES

 ---------------------------------------------

ALTER PROCEDURE USP_SAVE_PRODUCTS
@PRODUCT_NAME VARCHAR(50),
@PRODUCT_COUNT INT OUTPUT
AS
BEGIN
 INSERT INTO PRODUCTION.PRODUCTS(PRODUCT_NAME) VALUES(@PRODUCT_NAME)
 SELECT @PRODUCT_COUNT=COUNT(*) FROM PRODUCTION.PRODUCTS
 WHERE PRODUCT_NAME=@PRODUCT_NAME
 RETURN @PRODUCT_COUNT
 END;

DECLARE @COUNT INT;
EXEC USP_SAVE_PRODUCTS
@PRODUCT_NAME='ABC',
@PRODUCT_COUNT=@COUNT OUTPUT
SELECT @COUNT AS 'PRODUCTS COUNT'


-----------------------------------------------------

CREATE VIEW PRODUCTION_BRANDS_INFO
AS
SELECT * FROM PRODUCTION.PRODUCTS
SELECT * FROM PRODUCTION_BRANDS_INFO

ALTER PROCEDURE PRODUCTION_BRAND_PRO
@PRODUCT_NAME VARCHAR(20)
AS
BEGIN
INSERT INTO PRODUCTION_BRANDS_INFO(PRODUCT_NAME) VALUES(@PRODUCT_NAME)
SELECT * FROM PRODUCTION_BRAND_PRO 
END;

EXEC PRODUCTION_BRAND_PRO
SELECT * FROM PRODUCTION_BRAND_PRO WHERE PRODUCT_NAME='TREK'

DECLARE @COUNT INT;
EXEC USP_SAVE_PRODUCTS
@PRODUCT_NAME='ABC',
@PRODUCT_COUNT=@COUNT OUTPUT
SELECT @COUNT AS 'PRODUCTS COUNT'



SELECT P.BRAND_ID,P.BRAND_NAME
FROM PRODUCTION_BRANDS P

SELECT * FROM PRODUCTION_BRANDS_INFO

-------------------------TRY CATCH------------------------
CREATE PROCEDURE USP_DIVIDE
@A DECIMAL,
@B DECIMAL,
@C DECIMAL OUTPUT
AS
BEGIN
   BEGIN TRY
      SET @C=@A/@B;
   END TRY
   BEGIN CATCH
        SELECT 
		ERROR_NUMBER() AS 'ERROR NUMBER',
		ERROR_MESSAGE() AS 'ERROR MESSAGE',
		ERROR_LINE() AS 'LINE NO',
		ERROR_PROCEDURE() AS 'SP NAME'
   END CATCH
END;

DECLARE @R DECIMAL;
EXEC USP_DIVIDE 10,0,@R OUTPUT
PRINT @R 

ALTER PROCEDURE USP_MULTIPLY
@A INT,
@B INT,
@C INT OUTPUT
AS BEGIN 
   BEGIN TRY
      SET @C='ABC'*@A;
	  
   END TRY
   BEGIN CATCH
      SELECT 
		ERROR_NUMBER() AS 'ERROR NUMBER',
		ERROR_MESSAGE() AS 'ERROR MESSAGE',
		ERROR_LINE() AS 'LINE NO',
		ERROR_PROCEDURE() AS 'SP NAME'
   END CATCH
END;

DECLARE @R INT;
EXEC  USP_MULTIPLY 10.2,',@R OUTPUT
PRINT @R 


